# Generated by Django 3.0.5 on 2020-10-24 15:15

import app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.CharField(max_length=10)),
                ('disease_name', models.CharField(max_length=100)),
                ('symptom_details', djongo.models.fields.ArrayField(model_container=app.models.Symptom_detail)),
            ],
        ),
        migrations.CreateModel(
            name='symptom',
            fields=[
                ('symptom_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(max_length=100)),
            ],
        ),
    ]
