# Generated by Django 3.0.5 on 2020-11-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disease_disease_symptom_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='symptom_description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
