# Generated by Django 3.0.5 on 2020-11-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201110_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('userResponses', models.CharField(max_length=1000)),
                ('userResults', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('isFeedbackGiven', models.IntegerField()),
                ('feedbackRating', models.IntegerField()),
                ('feedbackText', models.CharField(max_length=5000)),
            ],
        ),
    ]
