# Generated by Django 3.0.5 on 2020-11-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_symptom_symptom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('userResponses', models.CharField(max_length=1000)),
                ('userResults', models.CharField(max_length=300)),
                ('create_date', models.DateField()),
                ('modify_date', models.DateField()),
            ],
        ),
    ]
