# Generated by Django 3.0.5 on 2020-11-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_symptom',
            name='all_symptoms',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
