# Generated by Django 3.0.5 on 2020-12-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_disease_symptom_all_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='remedies',
            field=models.CharField(default='', max_length=500),
        ),
    ]
