# Generated by Django 3.0.5 on 2020-12-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_disease_remedies'),
    ]

    operations = [
        migrations.CreateModel(
            name='County_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=50)),
                ('all_towns', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GP_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=800)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('mapLink', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
